[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
google-sheets4 = "*"
serde = "^1.0"
serde_json = "^1.0"
hyper = "*"
hyper-rustls = "*"

